//
//
export const TEST_SECURE_REQUEST = 'TEST_SECURE_REQUEST'
export const TEST_SECURE_SUCCESS = 'TEST_SECURE_SUCCESS'
export const TEST_SECURE_FAIL = 'TEST_SECURE_FAIL'

export const TEST_PUBLIC_REQUEST = 'TEST_PUBLIC_REQUEST'
export const TEST_PUBLIC_SUCCESS = 'TEST_PUBLIC_SUCCESS'
export const TEST_PUBLIC_FAIL = 'TEST_PUBLIC_FAIL'
